### ISSUE TITLE
Publish new version to crates.io

### ISSUE THREAD

**Issue by Shizcow** [lise-henry/rust-ispell#3]
Sorry if this is necro-bumping this project, but this crate fits my needs better than anything else out there.

The version on crates.io is out of date. Between that version, and the tip of master, is a bugfix that's stabilized the checking of "aa". This was discussed in issue #1 and was resolved there too.

All that needs to be done is bump the version and publish to crates.io.

**Comment by crowdagger** [comment]
Oh, yeah, I should have done that at the time, but now it's published. Glad if this project is useful to you!

**Comment by Shizcow** [comment]
Just checked, and everything's working great. Thanks a ton for updating.
